// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations need the session pooler (DIRECT_URL) — the transaction pooler
    // that DATABASE_URL points to doesn't support the advisory locks/DDL Prisma
    // migrate uses.
    url: process.env["DIRECT_URL"],
  },
});
